### POST /auth/login - Login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"email": "ibnkhayat.mohamed642@gmail.com",
	"password": "gestionnaire"
}

# {
# 	"email": "john.doe@gmail.com",
# 	"password": "P@ssw0rd!2022"
# }

### PATCH /auth/change-password - Change Password
PATCH {{baseUrl}}/auth/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"temporaryPassword": "%iFS7[8g9m[i",
	"newPassword": "P@ssw0rd!2022"
}

### GET /users - Get All Users
GET {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{accessToken}}

### GET /users/{id} - Get User By Id
GET {{baseUrl}}/users/2 HTTP/1.1
Authorization: Bearer {{accessToken}}

### POST /users - Create User
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"firstName": "John",
	"lastName": "Doe",
	"profileId": 2,
	"email": "john.doe@gmail.com"
}

### PATCH /users/{id} - Update User
PATCH {{baseUrl}}/users/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"firstName": "Johnathan",
	"profileId": 1
}

### DELETE /users/{id} - Delete User
DELETE {{baseUrl}}/users/2 HTTP/1.1
Authorization: Bearer {{accessToken}}

### GET /profiles - Get All Profiles
GET {{baseUrl}}/profiles HTTP/1.1
Authorization: Bearer {{accessToken}}

### GET /profiles/{id} - Get Profile By Id
GET {{baseUrl}}/profiles/2 HTTP/1.1
Authorization: Bearer {{accessToken}}

### POST /profiles - Create Profile
POST {{baseUrl}}/profiles HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"name": "Agent de relance"
}

### POST /profiles/{id}/permissions - Add Permissions To Profile
PUT {{baseUrl}}/profiles/2/permissions/2 HTTP/1.1
Authorization: Bearer {{accessToken}}

### DELETE /profiles/{id}/permissions/{id} - Remove Permission From Profile
DELETE {{baseUrl}}/profiles/2/permissions/1 HTTP/1.1
Authorization: Bearer {{accessToken}}

### GET /permissions - Get All Permissions
GET {{baseUrl}}/permissions HTTP/1.1
Authorization: Bearer {{accessToken}}