/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}", "./node_modules/flowbite/**/*.js"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#f3f9ec",
          100: "#e7f3d9",
          200: "#d0e9b3",
          300: "#b9df8d",
          400: "#9fcf56",
          500: "#89be2d",
          600: "#7eb324",
          700: "#77ad1a",
          800: "#619013",
          900: "#4a6e0e",
        },
        // secondary: {
        //   50: "#f2f2f3",
        //   100: "#e1e2e3",
        //   200: "#c7c8ca",
        //   300: "#aeafb1",
        //   400: "#9a9b9d",
        //   500: "#868789",
        //   600: "#72747a",
        //   700: "#5e6068",
        //   800: "#4a4c56",
        //   900: "#363844",
        // },
        warning: {
          50: "#fef9ec",
          100: "#fef0d0",
          200: "#fde3a8",
          300: "#fcd680",
          400: "#fbca5f",
          500: "#f2b42b",
          600: "#e29f24",
          700: "#d1891e",
          800: "#c07417",
          900: "#a75f11",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        body: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      transitionProperty: {
        width: "width",
      },
      textDecoration: ["active"],
      minWidth: {
        kanban: "28rem",
      },
    },
  },
  plugins: [require("flowbite/plugin")],
};
